mitigation/urls.py
from django.urls import path
from .views import index

urlpatterns = [
    path('', index, name = 'mitigation')
]

tk1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from index.forms import CustomAuthForm
from index import views as core_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('about/', include('about.urls')),
    path('feedback/', include('feedback.urls')),
    path('kontak_darurat/', include('kontak_darurat.urls')),
    path('mitigation/', include('mitigation.urls')),

    path('login/', auth_views.LoginView.as_view(template_name='login.html', authentication_form=CustomAuthForm), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html', next_page='/'), name = 'logout'),
    path('register/', core_views.signup, name='register'),
]

mitigation/models.py
from django.db import models

# Create your models here.

class Bencana(models.Model):
    category = models.CharField(blank=False,max_length=20)

mitigation/forms.py
from django import forms

BENCANA_CHOICES = [
    ('Polusi Udara','Polusi Udara'),
    ('Banjir','Banjir'),
    ('Gempa Bumi','Gempa Bumi'),
    ('Kebakaran','Kebakaran')
     ]

class BencanaForm(forms.Form):
    category = forms.ChoiceField(
                        widget=forms.Select,
                        choices=BENCANA_CHOICES)
    
    attrs = {
        'class': 'form-control',
    }

mitigation/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Bencana
from .forms import BencanaForm

# Create your views here.

def index(request):
    response = {"bencana_form": BencanaForm}
    bencanas = Bencana.objects.all().values()
    response['bencanas'] = bencanas
    return render(request, 'mitigation.html', response)
    return HttpResponse("Mitigasi")

    if request.method == 'GET':
        form = BencanaForm(request.GET)
        try:
            bencana = request.GET.get('bencana')
            response['pilih bencana'] = Bencana.objects.get(bencana=bencana)
        except:
            response['pilih bencana'] = Bencana.objects.get(bencana='Emergency Kit')
    else:
        response['pilih bencana'] = Bencana.objects.get(bencana='Emergency Kit')

    return render(request, 'mitigation.html', response)

mitigation/templates/mitigation.html
<!DOCTYPE html>
<html>
<head>
    <title>Mitigasi</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <link rel="stylesheet" href="{% static 'css/about.css' %}" />
	
	<style>
		.bg{
			max-width:100%;
			max-height:100%;
		}
		
	</style>
</head>

<body>
{% include "navbar.html" %}
<div id="home">
				<div class="gallery">
					<br><br><br>
					<h1 class="text-center">Pedoman Kesiapsiagaan Hadapi Bencana</h1>
					<br><br><br>
					<div class="row mb-2">
						<img src="{% static 'images/mitigation/homebackground.jpg' %}" class="bg">
					</div>
					
					<div class="row mb-2">
					<div class="col-md-1">
					</div>
						<div class="col-md-10">
						<br>
						<form method="GET">
							<table>
								<tr><th><label for="id_category">Kartu Darurat:‎‎‏‏‎ ‎‏‏‎ ‎</label></th>
								<td><select name="category" id="id_category">
									<option value="N">---Pilih Kartu---</option>
									<option value="EK">EMERGENCY KIT</option>
									<option value="P">POLUSI UDARA</option>
									<option value="B">BANJIR</option>
									<option value="GB">GEMPA BUMI</option>
									<option value="K">KEBAKARAN</option>
							</select></td></tr>
							</table>
							<br>
							<button type="Submit">Pilih</button>
						</form>
						<!--<table>
							
						</table>-->
						</div>
					<div class="col-md-1">
					</div>
					</div>
					
					<div class="row mb-2">
					<div class="col-md-1">
					</div>
						<div class="col-md-10">
						<br><br><br>
						<br><br><br>
						<h1 class="text-center">:: EMERGENCY KIT ::</h1>
						<br><br><br>
							<iframe width="854" height="480" src="https://www.youtube.com/embed/eSq6_rX_kOc"></iframe>
						</div>
					<div class="col-md-1">
					</div>
					</div>
					
					<br><br><br>
					<br><br><br>
					
					<div class="row mb-3">
					<div class="col-md-1">
					</div>
						<div class="col-md-10">
							<h1 class="text-center">:: POLUSI UDARA ::</h1>
						</div>
					<div class="col-md-1">
					</div>
					</div>
					
					<div class="row mb-2">
					<div class="col-md-1">
					</div>
						<div class="col-md-5">
						<br><br><br>
						<br><br><br>
							<div class="card">
								<img src="{% static 'images/mitigation/polusiudara.jpg'%}" alt="Park" class="card-img-top">
							</div>
						</div> 
						<div class="col-md-5">
						<br><br><br>
						<br><br><br>
							<iframe width="420" height="325" src="https://www.youtube.com/embed/aK3BWmDC0H4"></iframe>
						</div>
					<div class="col-md-1">
					</div>
					</div>
					
					<br><br><br>
					<br><br><br>
					
					<div class="row mb-3">
					<div class="col-md-1">
					</div>
						<div class="col-md-10">
							<h1 class="text-center">:: BANJIR ::</h1>
						</div>
					<div class="col-md-1">
					</div>
					</div>
					
					<div class="row mb-2">
					<div class="col-md-1">
					</div>
						<div class="col-md-5">
						<br><br><br>
						<br><br><br>
							<div class="card">
								<img src="{% static 'images/mitigation/banjir.jpg'%}" alt="Park" class="card-img-top">
							</div>
						</div> 
						<div class="col-md-5">
						<br><br><br>
						<br><br><br>
							<iframe width="420" height="325" src="https://www.youtube.com/embed/dvuGyLZh-og"></iframe>
						</div>
					<div class="col-md-1">
					</div>
					</div>
					
					<br><br><br>
					<br><br><br>
					
					<div class="row mb-3">
					<div class="col-md-1">
					</div>
						<div class="col-md-10">
							<h1 class="text-center">:: GEMPA BUMI ::</h1>
						</div>
					<div class="col-md-1">
					</div>
					</div>
					
					<div class="row mb-2">
					<div class="col-md-1">
					</div>
						<div class="col-md-5">
						<br><br><br>
						<br><br><br>
							<div class="card">
								<img src="{% static 'images/mitigation/gempabumi.jpg'%}" alt="Park" class="card-img-top">
							</div>
						</div> 
						<div class="col-md-5">
						<br><br><br>
						<br><br><br>
							<iframe width="420" height="325" src="https://www.youtube.com/embed/liw3hnAyV8U"></iframe>
						</div>
					<div class="col-md-1">
					</div>
					</div>
					
					<br><br><br>
					<br><br><br>
					
					<div class="row mb-3">
					<div class="col-md-1">
					</div>
						<div class="col-md-10">
							<h1 class="text-center">:: KEBAKARAN ::</h1>
						</div>
					<div class="col-md-1">
					</div>
					</div>
					
					<div class="row mb-2">
					<div class="col-md-1">
					</div>
						<div class="col-md-5">
						<br><br><br>
						<br><br><br>
							<div class="card">
								<img src="{% static 'images/mitigation/kebakaran.jpg'%}" alt="Park" class="card-img-top">
							</div>
						</div> 
						<div class="col-md-5">
						<br><br><br>
						<br><br><br>
							<iframe width="420" height="325" src="https://www.youtube.com/embed/dO1t_xfQhHk"></iframe>
						</div>
					<div class="col-md-1">
					</div>
					</div>
					
					<br><br><br>
					<br><br><br>
					
				</div>
			  
	</div>

</body>

</html>